import { readFileSync, writeFileSync, existsSync, mkdirSync } from 'fs';
import { join, dirname } from 'path';
import { fileURLToPath } from 'url';

// Configuración para emular __dirname en ES Modules nativos
const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

class SDLCompiler {

    constructor(idlFile = 'saludo.sdl') {
        this.idlPath = join(process.cwd(), idlFile);
        this.outputDirs = {
            client: join(process.cwd(), 'client'),
            server: join(process.cwd(), 'server')
        };
    }

    compile() {
        try {
            console.log(`[🚀 COMPILER] Iniciando compilación de de: ${this.idlPath}`);
            
            const metadata = this.parseSDL();
            this.prepareDirectories();
            this.generateArtifacts(metadata);
            
            console.log('\n[✨ SUCCESS] Arquitectura distribuida generada con éxito en /client y /server.');
        } catch (error) {
            console.error(`[❌ ERROR] Fallo en la compilación: ${error.message}`);
        }
    }

    // ----------------------------------------------------------------
    // 1. PARSER CORE: Extracción y limpieza de la Metadata del SDL
    // ----------------------------------------------------------------
    parseSDL() {
        if (!existsSync(this.idlPath)) {
            throw new Error(`Archivo contractual "${this.idlPath}" no encontrado.`);
        }

        const contenido = readFileSync(this.idlPath, 'utf-8');
        const lineas = contenido.split(/\r?\n/).map(line => line.trim());

        let port = '';
        let ip = '';
        let className = '';
        const methods = [];

        for (const linea of lineas) {
            if (!linea || linea.startsWith('}')) continue;

            if (linea.startsWith('@port:')) {
                port = linea.split(':')[1]?.trim();
            } else if (linea.startsWith('@ip:')) {
                ip = linea.split(':')[1]?.trim();
            } else if (linea.startsWith('@class ')) {
                className = linea.replace('@class ', '').replace('{', '').trim();
            } else if (linea.startsWith('@method ')) {
                methods.push(this.extractMethodMetadata(linea));
            }
        }

        if (!port || !ip || !className) {
            throw new Error('Formato SDL inválido. Faltan directivas obligatorias (@port, @ip o @class).');
        }

        return { port, ip, className, methods };
    }

    extractMethodMetadata(linea) {
        const textoCompleto = linea.replace('@method ', '').trim();
        const [nombreMetodo, paramsRaw] = textoCompleto.split('(');
        
        const parametros = paramsRaw
            ? paramsRaw.replace(')', '').split(',').map(p => p.trim()).filter(Boolean)
            : [];

        return {
            textoCompleto,
            nombre: nombreMetodo.trim(),
            parametros
        };
    }

    // ----------------------------------------------------------------
    // 2. INFRAESTRUCTURA: Inicialización del File System
    // ----------------------------------------------------------------
    prepareDirectories() {
        Object.values(this.outputDirs).forEach(dir => {
            if (!existsSync(dir)) {
                mkdirSync(dir, { recursive: true });
            }
        });
    }

    // ----------------------------------------------------------------
    // 3. ENGINE: Generación de código asíncrono limpio (ESM)
    // ----------------------------------------------------------------
    generateArtifacts(metadata) {
        const { className } = metadata;
        const { client: clientDir, server: serverDir } = this.outputDirs;

        // --- MOLDES LADO CLIENTE (STUBS) ---
        const codeClient = `// Auto-generated by SDL Compiler
export class ${className}Client {
    constructor() {
        console.log('[Base Client] Inicializando canal remoto para ${className}');
    }
}
`;

        const codeProxy = `// Auto-generated by SDL Compiler
import { ${className}Client } from './${className}Client.js';

export class ${className}Proxy extends ${className}Client {
    constructor() {
        super();
    }
}
`;

        const codeClientRSI = `// Auto-generated by SDL Compiler
import { ${className}Proxy } from './${className}Proxy.js';
import { createConnection } from 'net';

export class ${className}ClientRSI extends ${className}Proxy {
    constructor() {
        super();
        this.port = ${metadata.port};
        this.host = '${metadata.ip}';
    }
${metadata.methods.map(m => `
    async ${m.nombre}(${m.parametros.join(', ')}) {
        return new Promise((resolve, reject) => {
            const socket = createConnection({ port: this.port, host: this.host }, () => {
                const payload = JSON.stringify({ 
                    metodo: '${m.nombre}', 
                    args: [${m.parametros.join(', ')}] 
                });
                socket.write(payload);
            });

            socket.on('data', (buffer) => {
                const { resultado, error } = JSON.parse(buffer.toString());
                socket.end();
                if (error) return reject(new Error(error));
                resolve(resultado);
            });

            socket.on('error', reject);
        });
    }`).join('\n')}
}
`;

        // --- MOLDES LADO SERVIDOR (SKELETONS) ---
        const codeServerRSI = `// Auto-generated by SDL Compiler
import { createServer } from 'net';
import { ${className}BO } from './${className}BO.js';

export class ${className}ServerRSI {
    constructor() {
        this.port = ${metadata.port};
        this.bo = new ${className}BO();
    }

    iniciar() {
        const server = createServer((socket) => {
            socket.on('data', (buffer) => {
                try {
                    const { metodo, args } = JSON.parse(buffer.toString());
                    
                    switch (metodo) {
${metadata.methods.map(m => `                        case '${m.nombre}': {
                            const resultado = this.bo.${m.nombre}(...args);
                            socket.write(JSON.stringify({ resultado }));
                            break;
                        }`).join('\n')}
                        default:
                            socket.write(JSON.stringify({ error: \`Método '\${metodo}' no soportado.\` }));
                    }
                } catch (err) {
                    socket.write(JSON.stringify({ error: err.message }));
                }
            });
        });

        server.listen(this.port, () => {
            console.log(\`[🚀 SERVER SKELETON] Escuchando peticiones en puerto \${this.port}\`);
        });
    }
}
`;

        const codeBO = `// Template generated by SDL Compiler
// Implemente la lógica de negocio real dentro de esta clase.

export class ${className}BO {
${metadata.methods.map(m => `
    ${m.nombre}(${m.parametros.join(', ')}) {
        // TODO: Hardcodee su lógica de negocio o "Hola Mundo" aquí
        throw new Error("El método '${m.nombre}' requiere implementación manual.");
    }`).join('\n')}
}
`;

        // Escritura de archivos atómica
        writeFileSync(join(clientDir, `${className}Client.js`), codeClient);
        writeFileSync(join(clientDir, `${className}Proxy.js`), codeProxy);
        writeFileSync(join(clientDir, `${className}ClientRSI.js`), codeClientRSI);
        
        writeFileSync(join(serverDir, `${className}ServerRSI.js`), codeServerRSI);
        writeFileSync(join(serverDir, `${className}BO.js`), codeBO);
    }
}

// Inicialización del proceso
const compiler = new SDLCompiler('saludo.sdl');
compiler.compile();