/**
 * {{CLASS_NAME}}BO -- Business Object Interface
 * Generated by SDL Compiler | Luismi Architect
 *
 * Implements the actual server functionality for the operations
 * defined in the SDL.
 */
export class {{CLASS_NAME}}BO {
{{METODOS_BO}}
}
