import { {{CLASS_NAME}}ClientRSI } from './{{CLASS_NAME}}ClientRSI.js';

/**
 * Client App Main Driver
 * Generated by SDL Compiler | Luismi Architect
 *
 * Exposes the final Client application implementation, creating an instance
 * of the ClientRSI and calling its remote methods.
 */
async function main() {
    console.log("--- Initializing {{CLASS_NAME}} Client ---");
    const client = new {{CLASS_NAME}}ClientRSI();

    try {
        // Here you invoke the proxy functions
        // Example: const res = await client.metodoPrueba();
{{LLAMADAS_PRUEBA}}
    } catch(err) {
        console.error("Client side exception occurred:", err);
    }
}

main();