/**
 * {{CLASS_NAME}}Proxy -- Client Proxy Interface
 * Generated by SDL Compiler | Luismi Architect
 *
 * Defines the blueprint/interface of the service methods.
 * Forces the remote communication strategy to be implemented via inheritance.
 */
export class {{CLASS_NAME}}Proxy {
    constructor() {
        if (new.target === {{CLASS_NAME}}Proxy) {
            throw new TypeError("Cannot instantiate Proxy class directly (Abstract Class)");
        }
    }

{{METODOS_PROXY}}
}
