import { {{CLASS_NAME}}ServerRSI } from './{{CLASS_NAME}}ServerRSI.js';

/**
 * Main Server Wrapper
 * Generated by SDL Compiler
 *
 * Automates the instantiation and execution of the ServerRSI so that
 * the user does not have to create manual startup scripts.
 */
console.log("--- Initializing {{CLASS_NAME}} Server ---");
const server = new {{CLASS_NAME}}ServerRSI();
server.iniciar();
